name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: List Directory Contents for Debugging
      run: ls -R
      # Lists all files and folders to confirm the exact path to `pom.xml`

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -f app/pom.xml

    - name: Dependency Track SBOM Upload
      uses: DependencyTrack/gh-upload-sbom@v3
      with:
        serverHostname: 'http://localhost:8081'
        apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
        projectName: 'Amazin'
        projectVersion: '0.0.1-SNAPSHOT'
        bomFilename: "app/target/classes/META-INF/sbom/application.cdx.json"
        autoCreate: true